package org.nikiforova.solutions.easy.string;

import java.util.Arrays;

public class TheDifferenceBetweenStrings {
    /**
     * @param s - a string
     * @param t - a string, that is generated by random shuffling string s and then add one more letter at a random position
     * @return the letter that was added to t
     * 0 <= s.length <= 1000
     * t.length == s.length + 1
     * s and t consist of lowercase English letters
     */
    public static char findTheDifference(String s, String t) {
        if (s.length() == 0) return t.charAt(0);
        char[] sChars = s.toCharArray();
        char[] tChars = t.toCharArray();
        Arrays.sort(sChars);
        Arrays.sort(tChars);
        for (int i = 0; i < sChars.length; i++) {
            if (tChars[i] != sChars[i]) {
                return tChars[i];
            }
        }
        return tChars[tChars.length - 1];
    }
}
